import = ["/home/shiva/.config/alacritty/themes/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.85
# opacity = 0.3

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
