import = ["/home/shiva/.config/alacritty/themes/catppuccin-mocha.toml"]


live_config_reload = true

# [[keyboard.bindings]]
# key = "L"
# mods = "Control|Shift"
# action = "ClearHistory"
# action = "ClearLogNotice"

[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux"]
# args = ["-l", "-c", "tmux attach || tmux"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

normal.family = "JetBrainsMonoNerdFont"
normal.style = "Regular"

bold.family = "JetBrainsMonoNerdFont"
bold.style = "Bold"

bold_italic.family = "JetBrainsMonoNerdFont"
bold_italic.style = "Bold Italic"

italic.family = "JetBrainsMonoNerdFont"
italic.style = "Italic"

offset.x = 0
offset.y = 0

glyph_offset.x = 0
glyph_offset.y = 0

[mouse]
hide_when_typing = true


[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3
# auto_scroll = true


[window]
opacity = 1
dynamic_padding = false

padding.x = 6
padding.y = 6

decorations = "full"

startup_mode = "Maximized"

class.general = "Alacritty"
class.instance = "Alacritty"

